export  const darkScheme ={
        textColor: "text-gray-400",
        logoTextColor: "text-[#9796b2]",
        backgroundColor: "bg-[#2b2c37]",
        HoverSelectBorderColor: "border-[#2b2c37]",
        otherBorder: "border-zinc-600",
        hoverSelect: "hover:border-[#2b2c37] hover:opacity-80",
        activeSelect: "border-[#2b2c37]",
        hoverText: "hover:text-violet-900",
        hoverBg: "hover:bg-[#a8a4ff]",
        activeText: "text-gray-300",
        hoverFill: "hover:fill-violet-900",
        activeFill: "fill-gray-300",
        divOne: "bg-indigo-600/70",
        divTwo: "bg-indigo-400/70",
        divThree: "bg-indigo-200/70",
        toggleBg: "bg-indigo-100/30",
        toggleSvgFill: "fill-gray-800",
        toggleButtonBg: "bg-[#635fc7]",
        toggleCircle: "bg-gray-300",
        svgFill: "fill-gray-300",
}