export const lightScheme ={
        textColor: "text-gray-400",
        logoTextColor: "text-indigo-950",
        backgroundColor: "bg-white",
        HoverSelectBorderColor: "border-white",
        otherBorder: "border-gray-200",
        hoverSelect: "hover:border-indigo-50",
        activeSelect: "border-white",
        hoverText: "hover:text-violet-800",
        activeText: "text-white",
        hoverFill: "hover:fill-violet-800",
        hoverBg: "hover:bg-indigo-100/70",
        activeFill: "fill-white",
        divOne: "bg-indigo-800/70",
        divTwo: "bg-indigo-600/70",
        divThree: "bg-indigo-400/70",
        toggleBg: "bg-indigo-100/50",
        toggleSvgFill: "fill-gray-400",
        toggleButtonBg: "bg-indigo-400",
        toggleCircle: "bg-white",
        svgFill: "fill-white",
}